### ISSUE TITLE
Error: getaddrinfo ENOENT

### ISSUE THREAD

**Issue by nkhine** [defunct/node-ec2#7]
i have this:

```
$ node app.js                                                                                                                                                                  ""

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
          ^
Error: getaddrinfo ENOENT
    at errnoException (dns.js:31:11)
    at Object.onanswer [as oncomplete] (dns.js:140:16)
```

here is the code:

```
var ec2 = require("ec2")
, fs = require("fs");

// Read in the configuration above.
var configuration = JSON.parse(fs.readFileSync("configuration.json", "utf8"));

// Create an ec2 function that uses your configuration.
ec2 = ec2(configuration)

// Run an instance and wait for it to become ready.
ec2("RunInstances", {
  ImageId: "ami-5d704b29", KeyName: "micros-ie", InstanceType: "t1.micro"
}, function (error, response) {
  if (error) {
    throw error
  }
  reservationId   = response.reservationId;
  instanceId      = response.instancesSet[0].instanceId;
  ready = function () {
    ec2("DescribeInstances", function (error, struct) {
      if (error) {
        throw error;
      }
      var reservation = struct.reservationSet.filter(function (reservation) {
        return reservation.reservationId == reservationId;
      })[0];
      var instance = reservation.instancesSet.filter(function (instance) {
        return instance.instanceId == instanceId;
      })[0];
      return instance.instanceState.name == "running";
      if (instance.instanceState.name == "running") {
        console.log("Instance created with id: " + instanceId);
      } else {
        setTimeout(ready, 500);
      }
    });
  };
  ready();
});
```

**Comment by bigeasy** [comment]
Is DNS failing? What value did you set for the `endpoint`?

**Comment by nkhine** [comment]
sorry, i just found the project and am unsure how to specify the endpoint?

in the configuration.json file, i have this:

{ "key": "AWS_ACCESS_KEY_ID"
, "secret": "AWS_SECRET_ACCESS_KEY"
, "endpoint": "ec2.eu-west-1.amazonaws.com"
}

is this correct waay to do it?

**Comment by bigeasy** [comment]
Just `eu-west-1`.

**Comment by bigeasy** [comment]
I'm going to leave this issue open. The library should throw an exception if it is missing configuration.

**Comment by nkhine** [comment]
ok, thanks
